apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  labels:
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: wordpress-0
#    statefulset.kubernetes.io/pod-name: wordpress-1
#    statefulset.kubernetes.io/pod-name: wordpress-2
#    statefulset.kubernetes.io/pod-name: wordpress-3
#    statefulset.kubernetes.io/pod-name: wordpress-4

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
