apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
                volumeMounts:
        - name: wordpress-pvc
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: wordpress-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "wordpress"
      resources:
        requests:
          storage: 1Gi
