apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: wp
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - name: http
          containerPort: 8080
        # volumeMounts:
        # - name: wordpress-pvc
        #   mountPath: /usr/share/nginx/html
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql
            # - name: WORDPRESS_DB_USER
            #   value: admin
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password

  # volumeClaimTemplates:
  # - metadata:
  #     name: wordpress
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
