apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: wordpress
  replicas: 5
  template:
    metadata:
      labels:
        app: wordpress
        tier: wp
    spec:
      containers:
      - name: wordpress
        image: wordpress:4
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql
            # - name: WORDPRESS_DB_USER
            #   value: admin
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
